/* Generated By:JavaCC: Do not edit this line. HelloConstants.java */
//像java�?样的包名定义,生成的java文件会带上此包名
package org.openatom.javacc.helloworld;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HelloConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HELLO = 2;
  /** RegularExpression Id. */
  int IDENTITY = 3;
  /** RegularExpression Id. */
  int EXCLAMATION = 4;
  /** RegularExpression Id. */
  int COMMA = 5;
  /** RegularExpression Id. */
  int EOL = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<HELLO>",
    "<IDENTITY>",
    "\"!\"",
    "\",\"",
    "<EOL>",
  };

}
