// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: color.proto
// Protobuf Java Version: 4.33.0

package org.bluebridge.protobuf.proto;

@com.google.protobuf.Generated
public final class ColorProto extends com.google.protobuf.GeneratedFile {
  private ColorProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 0,
      /* suffix= */ "",
      "ColorProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 颜色枚举定义
   * </pre>
   *
   * Protobuf enum {@code org.bluebridge.protobuf.color.Color}
   */
  public enum Color
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 枚举值必须从 0 开始，通常用作默认值
     * </pre>
     *
     * <code>COLOR_RED = 0;</code>
     */
    COLOR_RED(0),
    /**
     * <code>COLOR_GREEN = 1;</code>
     */
    COLOR_GREEN(1),
    /**
     * <code>COLOR_BLUE = 2;</code>
     */
    COLOR_BLUE(2),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "Color");
    }
    /**
     * <pre>
     * 枚举值必须从 0 开始，通常用作默认值
     * </pre>
     *
     * <code>COLOR_RED = 0;</code>
     */
    public static final int COLOR_RED_VALUE = 0;
    /**
     * <code>COLOR_GREEN = 1;</code>
     */
    public static final int COLOR_GREEN_VALUE = 1;
    /**
     * <code>COLOR_BLUE = 2;</code>
     */
    public static final int COLOR_BLUE_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Color valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Color forNumber(int value) {
      switch (value) {
        case 0: return COLOR_RED;
        case 1: return COLOR_GREEN;
        case 2: return COLOR_BLUE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Color>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Color> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Color>() {
            public Color findValueByNumber(int number) {
              return Color.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.bluebridge.protobuf.proto.ColorProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Color[] VALUES = values();

    public static Color valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Color(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.bluebridge.protobuf.color.Color)
  }

  public interface ColorMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.bluebridge.protobuf.color.ColorMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.bluebridge.protobuf.color.Color color = 1;</code>
     * @return The enum numeric value on the wire for color.
     */
    int getColorValue();
    /**
     * <code>.org.bluebridge.protobuf.color.Color color = 1;</code>
     * @return The color.
     */
    org.bluebridge.protobuf.proto.ColorProto.Color getColor();

    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * <pre>
   * 包含颜色字段的消息
   * </pre>
   *
   * Protobuf type {@code org.bluebridge.protobuf.color.ColorMessage}
   */
  public static final class ColorMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.bluebridge.protobuf.color.ColorMessage)
      ColorMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "ColorMessage");
    }
    // Use ColorMessage.newBuilder() to construct.
    private ColorMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ColorMessage() {
      color_ = 0;
      description_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bluebridge.protobuf.proto.ColorProto.internal_static_org_bluebridge_protobuf_color_ColorMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bluebridge.protobuf.proto.ColorProto.internal_static_org_bluebridge_protobuf_color_ColorMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bluebridge.protobuf.proto.ColorProto.ColorMessage.class, org.bluebridge.protobuf.proto.ColorProto.ColorMessage.Builder.class);
    }

    public static final int COLOR_FIELD_NUMBER = 1;
    private int color_ = 0;
    /**
     * <code>.org.bluebridge.protobuf.color.Color color = 1;</code>
     * @return The enum numeric value on the wire for color.
     */
    @java.lang.Override public int getColorValue() {
      return color_;
    }
    /**
     * <code>.org.bluebridge.protobuf.color.Color color = 1;</code>
     * @return The color.
     */
    @java.lang.Override public org.bluebridge.protobuf.proto.ColorProto.Color getColor() {
      org.bluebridge.protobuf.proto.ColorProto.Color result = org.bluebridge.protobuf.proto.ColorProto.Color.forNumber(color_);
      return result == null ? org.bluebridge.protobuf.proto.ColorProto.Color.UNRECOGNIZED : result;
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (color_ != org.bluebridge.protobuf.proto.ColorProto.Color.COLOR_RED.getNumber()) {
        output.writeEnum(1, color_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, description_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (color_ != org.bluebridge.protobuf.proto.ColorProto.Color.COLOR_RED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, color_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, description_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.bluebridge.protobuf.proto.ColorProto.ColorMessage)) {
        return super.equals(obj);
      }
      org.bluebridge.protobuf.proto.ColorProto.ColorMessage other = (org.bluebridge.protobuf.proto.ColorProto.ColorMessage) obj;

      if (color_ != other.color_) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COLOR_FIELD_NUMBER;
      hash = (53 * hash) + color_;
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.bluebridge.protobuf.proto.ColorProto.ColorMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.ColorProto.ColorMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.ColorProto.ColorMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.ColorProto.ColorMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.ColorProto.ColorMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bluebridge.protobuf.proto.ColorProto.ColorMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.ColorProto.ColorMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.bluebridge.protobuf.proto.ColorProto.ColorMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.bluebridge.protobuf.proto.ColorProto.ColorMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.bluebridge.protobuf.proto.ColorProto.ColorMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.bluebridge.protobuf.proto.ColorProto.ColorMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.bluebridge.protobuf.proto.ColorProto.ColorMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.bluebridge.protobuf.proto.ColorProto.ColorMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 包含颜色字段的消息
     * </pre>
     *
     * Protobuf type {@code org.bluebridge.protobuf.color.ColorMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.bluebridge.protobuf.color.ColorMessage)
        org.bluebridge.protobuf.proto.ColorProto.ColorMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bluebridge.protobuf.proto.ColorProto.internal_static_org_bluebridge_protobuf_color_ColorMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bluebridge.protobuf.proto.ColorProto.internal_static_org_bluebridge_protobuf_color_ColorMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bluebridge.protobuf.proto.ColorProto.ColorMessage.class, org.bluebridge.protobuf.proto.ColorProto.ColorMessage.Builder.class);
      }

      // Construct using org.bluebridge.protobuf.proto.ColorProto.ColorMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        color_ = 0;
        description_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bluebridge.protobuf.proto.ColorProto.internal_static_org_bluebridge_protobuf_color_ColorMessage_descriptor;
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.ColorProto.ColorMessage getDefaultInstanceForType() {
        return org.bluebridge.protobuf.proto.ColorProto.ColorMessage.getDefaultInstance();
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.ColorProto.ColorMessage build() {
        org.bluebridge.protobuf.proto.ColorProto.ColorMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.bluebridge.protobuf.proto.ColorProto.ColorMessage buildPartial() {
        org.bluebridge.protobuf.proto.ColorProto.ColorMessage result = new org.bluebridge.protobuf.proto.ColorProto.ColorMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.bluebridge.protobuf.proto.ColorProto.ColorMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.color_ = color_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.description_ = description_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bluebridge.protobuf.proto.ColorProto.ColorMessage) {
          return mergeFrom((org.bluebridge.protobuf.proto.ColorProto.ColorMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bluebridge.protobuf.proto.ColorProto.ColorMessage other) {
        if (other == org.bluebridge.protobuf.proto.ColorProto.ColorMessage.getDefaultInstance()) return this;
        if (other.color_ != 0) {
          setColorValue(other.getColorValue());
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                color_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int color_ = 0;
      /**
       * <code>.org.bluebridge.protobuf.color.Color color = 1;</code>
       * @return The enum numeric value on the wire for color.
       */
      @java.lang.Override public int getColorValue() {
        return color_;
      }
      /**
       * <code>.org.bluebridge.protobuf.color.Color color = 1;</code>
       * @param value The enum numeric value on the wire for color to set.
       * @return This builder for chaining.
       */
      public Builder setColorValue(int value) {
        color_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.org.bluebridge.protobuf.color.Color color = 1;</code>
       * @return The color.
       */
      @java.lang.Override
      public org.bluebridge.protobuf.proto.ColorProto.Color getColor() {
        org.bluebridge.protobuf.proto.ColorProto.Color result = org.bluebridge.protobuf.proto.ColorProto.Color.forNumber(color_);
        return result == null ? org.bluebridge.protobuf.proto.ColorProto.Color.UNRECOGNIZED : result;
      }
      /**
       * <code>.org.bluebridge.protobuf.color.Color color = 1;</code>
       * @param value The color to set.
       * @return This builder for chaining.
       */
      public Builder setColor(org.bluebridge.protobuf.proto.ColorProto.Color value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000001;
        color_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.org.bluebridge.protobuf.color.Color color = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearColor() {
        bitField0_ = (bitField0_ & ~0x00000001);
        color_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 2;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.bluebridge.protobuf.color.ColorMessage)
    }

    // @@protoc_insertion_point(class_scope:org.bluebridge.protobuf.color.ColorMessage)
    private static final org.bluebridge.protobuf.proto.ColorProto.ColorMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.bluebridge.protobuf.proto.ColorProto.ColorMessage();
    }

    public static org.bluebridge.protobuf.proto.ColorProto.ColorMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ColorMessage>
        PARSER = new com.google.protobuf.AbstractParser<ColorMessage>() {
      @java.lang.Override
      public ColorMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ColorMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ColorMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.bluebridge.protobuf.proto.ColorProto.ColorMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_bluebridge_protobuf_color_ColorMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_bluebridge_protobuf_color_ColorMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013color.proto\022\035org.bluebridge.protobuf.c" +
      "olor\"X\n\014ColorMessage\0223\n\005color\030\001 \001(\0162$.or" +
      "g.bluebridge.protobuf.color.Color\022\023\n\013des" +
      "cription\030\002 \001(\t*7\n\005Color\022\r\n\tCOLOR_RED\020\000\022\017" +
      "\n\013COLOR_GREEN\020\001\022\016\n\nCOLOR_BLUE\020\002B-\n\035org.b" +
      "luebridge.protobuf.protoB\nColorProtoP\000b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_bluebridge_protobuf_color_ColorMessage_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_org_bluebridge_protobuf_color_ColorMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_bluebridge_protobuf_color_ColorMessage_descriptor,
        new java.lang.String[] { "Color", "Description", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
