/* Generated By:JavaCC: Do not edit this line. SqlConstants.java */
//像java�?样的包名定义,生成的java文件会带上此包名
package org.openatom.javacc.calculator;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int RIGHT_PARENTHESES = 2;
  /** RegularExpression Id. */
  int LEFT_PARENTHESES = 3;
  /** RegularExpression Id. */
  int COMMA = 4;
  /** RegularExpression Id. */
  int SEMICOLON = 5;
  /** RegularExpression Id. */
  int SINGLE_QUOTATION_MARK = 6;
  /** RegularExpression Id. */
  int COMMENT = 7;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int CHAR = 9;
  /** RegularExpression Id. */
  int CREATE = 10;
  /** RegularExpression Id. */
  int TABLE = 11;
  /** RegularExpression Id. */
  int VARIABLE_NAME = 12;
  /** RegularExpression Id. */
  int COMMENT_CONTENT = 13;
  /** RegularExpression Id. */
  int EOL = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\"\\\'\"",
    "\"COMMENT\"",
    "\"int\"",
    "\"char\"",
    "\"CREATE\"",
    "\"TABLE\"",
    "<VARIABLE_NAME>",
    "<COMMENT_CONTENT>",
    "<EOL>",
  };

}
