/* Generated By:JavaCC: Do not edit this line. SqlConstants.java */
//像java�?样的包名定义,生成的java文件会带上此包名
package org.openatom.javacc.sql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CREATE = 2;
  /** RegularExpression Id. */
  int IDENTITY = 3;
  /** RegularExpression Id. */
  int EXCLAMATION = 4;
  /** RegularExpression Id. */
  int COMMA = 5;
  /** RegularExpression Id. */
  int DOUHAO = 6;
  /** RegularExpression Id. */
  int EOL = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<CREATE>",
    "<IDENTITY>",
    "\";\"",
    "<COMMA>",
    "\",\"",
    "<EOL>",
  };

}
